[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.install]
cmds = ["mix local.hex --force", "mix local.rebar --force"]

[phases.build]
cmds = [
  "mix deps.get --only prod",
  "mix assets.deploy",
  "mix compile"
]

[start]
cmd = "mix ecto.setup && mix phx.server"
